name: Build Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - name: Checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - run: npx nx workspace-lint
      # - run: npx nx format:check --libs-and-apps=true
      - run: npx nx affected --target=lint --parallel
      - run: npx nx run-many --target=test --all --parallel --coverage --exclude=example-expo
      - run: npx nx affected --target=build --parallel --exclude=example-expo
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage/libs/ts-rest/core/lcov.info,./coverage/libs/ts-rest/express/lcov.info,./coverage/libs/ts-rest/nest/lcov.info,./coverage/libs/ts-rest/next/lcov.info,./coverage/libs/ts-rest/open-api/lcov.info,./coverage/libs/ts-rest/react-query/lcov.info
